"""Read-only tool gateway logic: registration, authorization, evidence.

See :mod:`opspilot.tools.executor` for the contract sources and the boundaries
this package deliberately does not cross.
"""

from .executor import (
    MAX_OPERATIONS_PER_RUN,
    MAX_TOOL_SECONDS_PER_RUN,
    ControlAuthority,
    ControlSnapshot,
    ControlUnavailable,
    EvidenceSink,
    QueryScope,
    ReadOnlyToolExecutor,
    ReadOnlyTransport,
    SystemClock,
    ToolRequest,
    TransportError,
    TransportRequest,
    TransportResponse,
    TransportResultTooLarge,
    TransportTimeout,
    TransportUnavailable,
)
from .outcomes import (
    DENIED_REASONS,
    ERROR_REASONS,
    PROJECTION_REVISION,
    EvidenceRecord,
    ToolOperation,
    ToolOutcome,
    Window,
)
from .registry import (
    FORBIDDEN_VERBS,
    MAX_REQUEST_TIMEOUT_SECONDS,
    MAX_RESULT_BYTES,
    READ_ONLY_VERBS,
    RESERVED_PARAMETERS,
    ParameterSpec,
    RegisteredTarget,
    TargetRegistry,
    ToolContractError,
    ToolRegistration,
    ToolRegistry,
)

__all__ = [
    "DENIED_REASONS",
    "ERROR_REASONS",
    "FORBIDDEN_VERBS",
    "MAX_OPERATIONS_PER_RUN",
    "MAX_REQUEST_TIMEOUT_SECONDS",
    "MAX_RESULT_BYTES",
    "MAX_TOOL_SECONDS_PER_RUN",
    "PROJECTION_REVISION",
    "READ_ONLY_VERBS",
    "RESERVED_PARAMETERS",
    "ControlAuthority",
    "ControlSnapshot",
    "ControlUnavailable",
    "EvidenceRecord",
    "EvidenceSink",
    "ParameterSpec",
    "QueryScope",
    "ReadOnlyToolExecutor",
    "ReadOnlyTransport",
    "RegisteredTarget",
    "SystemClock",
    "TargetRegistry",
    "ToolContractError",
    "ToolOperation",
    "ToolOutcome",
    "ToolRegistration",
    "ToolRegistry",
    "ToolRequest",
    "TransportError",
    "TransportRequest",
    "TransportResponse",
    "TransportResultTooLarge",
    "TransportTimeout",
    "TransportUnavailable",
    "Window",
]
