"""OpsPilot domain types and state machines.

Scope: the persistent object types and lifecycles listed in C3 section 4. No
persistence, no HTTP, no model calls. Every state machine is an explicit
``(state, trigger) -> state`` table that rejects any unlisted pair, so an
illegal transition is a deterministic error rather than an inferred move.

Three separations this package exists to hold:

1. Incident lifecycle and release observation status are independent machines.
   A ``ReleaseObservation`` is complete without any incident.
2. ``Run.execution`` and ``InvestigationResult`` are independent values.
   Finishing an attempt is not a finding, and neither is a recovery.
3. Human control is a conditional update on ``expected_version`` that
   increments the subject's ``control_generation``; global and per-target
   suspension is a separate scope state that outranks it.
"""

from .base import (
    DTO,
    Count,
    DomainError,
    ErrorCode,
    Positive,
    StateMachine,
    Text,
)
from .control import (
    ControlAction,
    ControlState,
    ObservationMode,
    ScopeVersions,
    SuspensionState,
    apply_control,
    automatic_investigation_allowed,
    check_scope_versions,
    event_intake_allowed,
    human_control_allowed,
    observation_sampling_allowed,
    release_targets,
    suspend_globally,
    suspend_targets,
)
from .evidence import (
    EVIDENCE_ADOPTION,
    TOOL_OPERATION,
    Evidence,
    EvidenceAdoption,
    QueryScope,
    QueryWindow,
    ToolOperation,
    ToolOperationState,
    advance_evidence,
    advance_tool_operation,
    counts_as_observed,
    may_enter_model_input,
    revoke_restricted,
)
from .intake import (
    InputEvent,
    Integration,
    Target,
    delivery_key,
    is_duplicate_delivery,
)
from .knowledge import (
    KNOWLEDGE_REVISION,
    POSTMORTEM,
    KnowledgeRevision,
    KnowledgeState,
    Postmortem,
    PostmortemState,
    advance_knowledge,
    advance_postmortem,
    publish_knowledge,
)
from .observation import (
    OBSERVATION_SESSION,
    HealthSample,
    ObservationPurpose,
    ObservationSession,
    ObservationSessionState,
    SampleAcceptance,
    SampleOutcome,
    adopt_sample,
    advance_session,
    confirms_health,
    evaluate_sample,
    extends_healthy_window,
    may_schedule_sample,
)
from .records import (
    EXPORT_OUTBOX,
    AuditRecord,
    ExportOutboxEntry,
    OutboxState,
    SubjectEvent,
    advance_outbox,
    next_sequence,
)
from .runs import (
    ACTIVE_RUN_EXECUTIONS,
    RUN_EXECUTION,
    BlockedReason,
    BudgetLedger,
    Conclusion,
    ConclusionAcceptance,
    InvestigationResult,
    ModelProfile,
    ModelStep,
    Run,
    RunExecution,
    ToolPlanEntry,
    advance_run,
    advance_watermark,
    claim_run,
    evaluate_conclusion,
    may_execute_tools,
    pending_tool_indices,
    step_id,
    tool_operation_id,
)
from .scheduling import (
    JOB,
    Job,
    JobState,
    Schedule,
    advance_job,
    check_execution_identity,
    claim_job,
    execution_key,
    may_execute,
    supersede_schedule,
)
from .subjects import (
    ACTIVE_INCIDENT_LIFECYCLES,
    ACTIVE_RELEASE_STATUSES,
    INCIDENT_LIFECYCLE,
    RELEASE_OBSERVATION,
    Incident,
    IncidentLifecycle,
    ReleaseIdentity,
    ReleaseObservation,
    ReleaseObservationPolicy,
    ReleaseStatus,
    SubjectRef,
    advance_incident,
    advance_release,
    disposition_for_new_anomaly,
    successor_observation,
)

STATE_MACHINES = {
    machine.name: machine
    for machine in (
        INCIDENT_LIFECYCLE,
        RELEASE_OBSERVATION,
        RUN_EXECUTION,
        TOOL_OPERATION,
        EVIDENCE_ADOPTION,
        JOB,
        OBSERVATION_SESSION,
        EXPORT_OUTBOX,
        POSTMORTEM,
        KNOWLEDGE_REVISION,
    )
}

__all__ = [
    "ACTIVE_INCIDENT_LIFECYCLES",
    "ACTIVE_RELEASE_STATUSES",
    "ACTIVE_RUN_EXECUTIONS",
    "AuditRecord",
    "BlockedReason",
    "BudgetLedger",
    "Conclusion",
    "ConclusionAcceptance",
    "ControlAction",
    "ControlState",
    "Count",
    "DTO",
    "DomainError",
    "EVIDENCE_ADOPTION",
    "EXPORT_OUTBOX",
    "ErrorCode",
    "Evidence",
    "EvidenceAdoption",
    "ExportOutboxEntry",
    "HealthSample",
    "INCIDENT_LIFECYCLE",
    "Incident",
    "IncidentLifecycle",
    "InputEvent",
    "Integration",
    "InvestigationResult",
    "JOB",
    "Job",
    "JobState",
    "KNOWLEDGE_REVISION",
    "KnowledgeRevision",
    "KnowledgeState",
    "ModelProfile",
    "ModelStep",
    "OBSERVATION_SESSION",
    "ObservationMode",
    "ObservationPurpose",
    "ObservationSession",
    "ObservationSessionState",
    "OutboxState",
    "POSTMORTEM",
    "Positive",
    "Postmortem",
    "PostmortemState",
    "QueryScope",
    "QueryWindow",
    "RELEASE_OBSERVATION",
    "RUN_EXECUTION",
    "ReleaseIdentity",
    "ReleaseObservation",
    "ReleaseObservationPolicy",
    "ReleaseStatus",
    "Run",
    "RunExecution",
    "STATE_MACHINES",
    "SampleAcceptance",
    "SampleOutcome",
    "Schedule",
    "ScopeVersions",
    "StateMachine",
    "SubjectEvent",
    "SubjectRef",
    "SuspensionState",
    "Target",
    "Text",
    "ToolOperation",
    "ToolOperationState",
    "ToolPlanEntry",
    "adopt_sample",
    "advance_evidence",
    "advance_incident",
    "advance_job",
    "advance_knowledge",
    "advance_outbox",
    "advance_postmortem",
    "advance_release",
    "advance_run",
    "advance_session",
    "advance_tool_operation",
    "advance_watermark",
    "apply_control",
    "automatic_investigation_allowed",
    "check_execution_identity",
    "check_scope_versions",
    "claim_job",
    "claim_run",
    "confirms_health",
    "counts_as_observed",
    "delivery_key",
    "disposition_for_new_anomaly",
    "evaluate_conclusion",
    "evaluate_sample",
    "event_intake_allowed",
    "execution_key",
    "extends_healthy_window",
    "human_control_allowed",
    "is_duplicate_delivery",
    "may_enter_model_input",
    "may_execute",
    "may_execute_tools",
    "may_schedule_sample",
    "next_sequence",
    "observation_sampling_allowed",
    "pending_tool_indices",
    "publish_knowledge",
    "release_targets",
    "revoke_restricted",
    "step_id",
    "successor_observation",
    "supersede_schedule",
    "suspend_globally",
    "suspend_targets",
    "tool_operation_id",
]
